<script >

</script>



<div id="hethongtt" class="easyui-tree">
	<li>
		<div class="tree-node" node-id="10" style="cursor: pointer;">
			<span class="tree-hit tree-expanded"></span><span
				class="tree-icon tree-folder tree-folder-open"></span><span
				class="tree-title"><?php echo $this->Tencoquan;?></span>
		</div>
		<ul>
		
		<!-- tre1 -->
		
			<li><div class="tree-node" style="cursor: pointer;">
					<span class="tree-indent"></span><span
						class="tree-hit tree-expanded"></span><span
						class="tree-icon tree-folder tree-folder-open"></span><span
						class="tree-title">Cơ quan hành chính</span>
				</div>
			<ul>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
							<span class="tree-indent"></span>
							<span class="tree-indent"></span>
							<span class="tree-indent"></span>
							
							<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/Thongtincoquan">Đơn vị hành chính</a></span>
						</div></li>
					
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/phongban">Phòng ban</a></span>
					</div></li>
			</ul></li>	
			
					
			<li><div class="tree-node" style="cursor: pointer;">
					<span class="tree-indent"></span><span
						class="tree-hit tree-expanded"></span><span
						class="tree-icon tree-folder tree-folder-open"></span><span
						class="tree-title">Thao tác dữ liệu</span>
				</div>
			<ul>
					
					
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								
								<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/dongia">Khai báo đầu năm</a></span>
						</div></li>
						
					
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								
								<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="">Sao lưu - phục hồi</a></span>
						</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
					<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/Cleardata">Đặt lại về dữ liệu gốc</a></span>
						</div></li>
			</ul></li>	
			
			
			
			<li><div class="tree-node" style="cursor: pointer;">
					<span class="tree-indent"></span><span
						class="tree-hit tree-expanded"></span><span
						class="tree-icon tree-folder tree-folder-open"></span><span
						class="tree-title">Phân quyền</span>
				</div>
			<ul>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								
								<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/Quanlynguoidung">Quản lý người dùng</a></span>
						</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								
								<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl();?>/default/Logs">Lịch sử thao tác</a></span>
					</div></li>
			</ul></li>	
					
				
			<!-- end tre1 -->
				
				
			
			
		
			
		</ul>
	</li>
</div>