<script >

</script>



<div id="websitett" class="easyui-tree">
	<li>
		<div class="tree-node" node-id="10" style="cursor: pointer;">
			<span class="tree-hit tree-expanded"></span><span
				class="tree-icon tree-folder tree-folder-open"></span><span
				class="tree-title"><?php echo $this->Tencoquan;?></span>
		</div>
		<ul>
		
		<!-- tre1 -->
		
			<li><div class="tree-node" style="cursor: pointer;">
					<span class="tree-indent"></span><span
						class="tree-hit tree-expanded"></span><span
						class="tree-icon tree-folder tree-folder-open"></span><span
						class="tree-title">Nghiệp vụ</span>
				</div>
			<ul>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
							<span class="tree-indent"></span>
							<span class="tree-indent"></span>
							<span class="tree-indent"></span>
							
							<span class="tree-icon tree-file"></span><span
								class="tree-title"><a href="<?php echo $this->baseUrl()?>/website/danhmuc">Danh mục</a></span>
						</div></li>
					
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/website/tintuc">Bài đăng</a></span>
					</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/website/binhluan">Bình luận</a></span>
					</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/website/lienket">Hình ảnh</a></span>
					</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/website/lienhe">Liên hệ</a></span>
					</div></li>
					<li><div class="tree-node" node-id="2" style="cursor: pointer;">
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
								<span class="tree-indent"></span>
						<span class="tree-icon tree-file"></span><span
						class="tree-title"><a href="<?php echo $this->baseUrl();?>/website/lichcongtac">Lịch công tác</a></span>
					</div></li>
			</ul></li>	
			
					
			
			
			
			
			
					
				
			<!-- end tre1 -->
				
				
			
			
		
			
		</ul>
	</li>
</div>