<div class="pager" >
    
    <ul>
       
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
              
              <li><a href="<?php echo $this->url().'?page='.$this->previous; ?>" class="first-page"></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url().'?page='.$this->previous; ?>" class="first-page"></a></li>
        <?php endif; ?>
        <!-- Numbered page links -->
        
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url().'?page='.$page; ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li ><a href="<?php echo $this->url().'?page='.$page; ?>"class="active"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
              <li><a href="<?php echo $this->url().'?page='.$this->next; ?>" class="last-page"></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url().'?page='.$this->next; ?>" class="last-page"></a></li>
        <?php endif; ?>
        
        </ul>
    
 </div>