<seciont id="content">
<div class="container">
<div class="main-content">
<div class="column-two-third single">
<?php if($this->Files):?>
  <ul>
  	<?php foreach ($this->Files as $value):?>
  		<li>
  		<p><a href="<?php echo $this->baseUrl().Websitefront_Model_Lichcongtac::getFileLink($value['File']) ?>"><?php echo $value['TieuDe']?></a>
  		(<?php echo $value['NgayTao']?>)</p>
  		
  		</li>
  	<?php endforeach;?>
  </ul>
<?php endif;?>
    </div><!-- end column two third -->
    
    </div><!-- end maint-content -->
    <!-- Left Sidebar -->
                <div class="column-one-third">


                    <div class="sidebar">
                        <h5 class="line"><span>Video</span></h5>
                        <?php if($this->Videos): ?>
                            <?php foreach($this->Videos as $value): ?>
                                <div class="full-frame" style="width: 320px; height: 300px; overflow: hidden;"><?php echo $value['Video']; ?></div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <style>
                            iframe{ width: 280px;}
                        </style>
                    </div>
                    
                    <div class="sidebar">
                    	<h5 class="line"><span>QUẢNG CÁO</span></h5>
                    	<?php if($this->QuangCao):?>
                        <ul class="ads125">
                        <?php foreach ($this->QuangCao as $value):?>
                        <?php if(Websitefront_Model_Lienket::checkImage($value['Id'])):?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getImage($value['Id']);?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php else:?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getDefaultImage();?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php endif;?>	
                        <?php endforeach;?>    
                        </ul>
                        <?php endif;?>
                    </div>
                    
                    <div class="sidebar">
				<div id="tabs">
					<ul>
						<li><a href="#tabs1">Gần nhất</a></li>
						<li><a href="#tabs2">Phổ biến</a></li>
						<li><a href="#tabs3">Bình luận</a></li>
					</ul>
					<div id="tabs1">
						<ul>
                                <?php if($this->TinMoiNhat):?>
                                <?php foreach ($this->TinMoiNhat as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo PublicdetailController::strimTitle($value['TieuDe']);?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?>   
                                </ul>
					</div>
					<div id="tabs2">
						<ul>
                                	 <?php if($this->TinXemNhieu):?>
                                <?php foreach ($this->TinXemNhieu as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
					<div id="tabs3">
						<ul>
                                	 <?php if($this->LuotBL):?>
                                <?php foreach ($this->LuotBL as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
				</div>
			</div>
                    
                    
                    
                </div>
                <!-- /Left Sidebar -->
    </div><!-- end container -->
</seciont>    