
<section id="content">
            <div class="container">
            	<!-- Main Content -->
                <?php echo $this->render('breadcrumbs/breadcrumbs.phtml');?>
                
                <div class="main-content">
                	<?php if($this->TinTuc):?>
                    <!-- Popular News -->
                    <?php $i=0;?>
                    
                	<div class="column-two-third">
                	<?php foreach ($this->TinTuc as $value):?>
                		<?php if($i<=1):?>
                    	<div class="outertight m-t-no <?php echo ($i==1)?'m-r-no': '';?>">
                            <div class="badg">
                                <p><a href="<?php echo $this->baseUrl().'/websitefront/'.Websitefront_Model_Tintuc::getLink($this->DanhMucChiTiet['Alias'], $value['Alias'])?>">Featured.</a></p>
                            </div>
                            <div class="flexslider">
                                <ul class="slides">
                                <li class="<?php echo $value['Id']?>"> 
                                <?php if(Websitefront_Model_Tintuc::checkImage($value['Id'])):?>
						<img src="<?php echo $this->baseUrl ().Websitefront_Model_Tintuc::getImage($value['Id'])?>" width="300px" height="162px" />
					<?php else :?>
						<img src="<?php echo $this->baseUrl(). Websitefront_Model_Tintuc::getDefaultImage()?>" width="300px" height="162px"  />
					<?php endif;?>	
                                 </li>
                                
                                    
                                </ul>
                            </div>
                            
                            <h6 class="regular"><a href="<?php echo $this->baseUrl().'/websitefront/'.Websitefront_Model_Tintuc::getLink($this->DanhMucChiTiet['Alias'], $value['Alias'])?>"><?php echo $value['TieuDe'];?></a></h6>
                            <span class="meta"><?php echo $value['NgayTao'];?></span>
                            <p><?php echo PublicdetailController::strimTitle($value['MoTa'], 20);?></p>
                        </div>
                        <?php else :?>
                       
                        <?php //if($this->TinTuc):?>
                        <?php if($i ==2):?>
                        	 <div class="outerwide">
                        	<ul class="block2">
                        <?php endif;?>	
                        	<?php //$count = count($this->TinTuc);?>
                        	<?php //$i = 0;?>
                        	<?php //foreach ($this->TinTuc as $value):?>
                        	<?php //print_r($value);die;?>
                                <li <?php echo (++$i%2==0)?"class='m-r-no'":''?>>
                                    <a href="<?php echo $this->baseUrl().'/websitefront/'.Websitefront_Model_Tintuc::getLink($this->DanhMucChiTiet['Alias'], $value['Alias'])?>">
                                    
                                    
                                    <?php if(Websitefront_Model_Tintuc::checkImage($value['Id'])):?>
						<img src="<?php echo $this->baseUrl ().Websitefront_Model_Tintuc::getImage($value['Id'])?>" width="140px" height="86px" class="alignleft" />
					<?php else :?>
						<img src="<?php echo $this->baseUrl(). Websitefront_Model_Tintuc::getDefaultImage()?>" width="140px" height="86px" class="alignleft"  />
					<?php endif;?>	
					</a>
                                    <p>
                                        <span><?php echo $value['NgayTao'];?></span>
                                        <a href="<?php echo $this->baseUrl().'/websitefront/'.Websitefront_Model_Tintuc::getLink($this->DanhMucChiTiet['Alias'], $value['Alias'])?>"><?php echo $value['TieuDe'];?></a>
                                    </p>
                                    <span class="rating"><span style="width:80%;"></span></span>
                                </li>
                              <?php //endforeach;?> 
                            
                             <?php //endif;?>
                        
                        <?php endif;?>
                        <?php $i++;?>
                        <?php endforeach;?>
                        <?php if($i>1):?>
                        </ul>
                    	</div>
                    	<?php endif;?>
                        <?php echo $this->paginationControl($this->TinTuc, 'Sliding', 'pagination.phtml')?>
                    	<?php endif;?>
                    		
                    </div>
                    <!-- /Popular News -->
                    
                </div>
                <!-- /Main Content -->
                
                <!-- Left Sidebar -->
                <div class="column-one-third">


                    <div class="sidebar">
                        <h5 class="line"><span>Video</span></h5>
                        <?php if($this->Videos): ?>
                            <?php foreach($this->Videos as $value): ?>
                                <div class="full-frame" style="width: 320px; height: 300px; overflow: hidden;"><?php echo $value['Video']; ?></div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <style>
                            iframe{ width: 280px;}
                        </style>
                    </div>
                    
                    <div class="sidebar">
                    	<h5 class="line"><span>QUẢNG CÁO</span></h5>
                    	<?php if($this->QuangCao):?>
                        <ul class="ads125">
                        <?php foreach ($this->QuangCao as $value):?>
                        <?php if(Websitefront_Model_Lienket::checkImage($value['Id'])):?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getImage($value['Id']);?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php else:?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getDefaultImage();?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php endif;?>	
                        <?php endforeach;?>    
                        </ul>
                        <?php endif;?>
                    </div>
                    
                    <div class="sidebar">
				<div id="tabs">
					<ul>
						<li><a href="#tabs1">Gần nhất</a></li>
						<li><a href="#tabs2">Phổ biến</a></li>
						<li><a href="#tabs3">Bình luận</a></li>
					</ul>
					<div id="tabs1">
						<ul>
                                <?php if($this->TinMoiNhat):?>
                                <?php foreach ($this->TinMoiNhat as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo PublicdetailController::strimTitle($value['TieuDe']);?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?>   
                                </ul>
					</div>
					<div id="tabs2">
						<ul>
                                	 <?php if($this->TinXemNhieu):?>
                                <?php foreach ($this->TinXemNhieu as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
					<div id="tabs3">
						<ul>
                                	 <?php if($this->LuotBL):?>
                                <?php foreach ($this->LuotBL as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
				</div>
			</div>
                    
                    
                    
                </div>
                <!-- /Left Sidebar -->
                
            </div>    
        </section>