<link rel="stylesheet" type="text/css" href="/ytetonghop/public/css/freeow/freeow.css" media="screen" />

<section id="content">
            <div class="container">
            	<!-- Main Content -->
                
                <?php echo $this->render('breadcrumbs/breadcrumbs.phtml');?>
                
             <div class="main-content">
                    
                    <!-- Single -->
                    <div class="column-two-third single">
                    	<div id="map">
                    		<?php echo $this->Bando['Bando'];?>
                    	</div>
                        <div class="outerwide">
                        	<h5 class="line"><span>Location.</span></h5>
                            <p>Mauris dapibus quam id turpis dignissim rutrum. Phasellus placerat nunc in nulla pretium pellentesque. Aliquam erat volutpat. In nec enim dui, in hendrerit enim. Vestibulum ante ipsum primis in faucibus adipcising elit. Lorem ipsum Dolor sit amet adipcising elit mauris dapibus dignisim. </p>
                            
                            <div class="contact-info">
                            	<p class="man"><i class="icon-location"></i>Creative Laboratory <br />77 New York Avenue, New York city, <br />USA 10000.</p>
                                <p class="phone"><i class="icon-phone"></i> Phone:  73 443 11 23. <br />Fax:  73 443 11 23.</p>
                                <p class="envelop"><i class="icon-mail"></i>Email: <a href="#">mail@page.com</a> <br /> Web: <a href="#">www.page.com</a></p> 
                            </div>
                        </div>
                        <div class="contact-form">
                        
                        <?php if($this->error):?>
                        	<?php foreach ($this->error as $value):?>
                        		<?php foreach ($value as $v):?>
                        		<?php if(!is_array($v)):?>
                        			<span style="color:red;font-size: 14px;"><?php echo $v?></span><br>
                        		<?php endif;?>	
                        		<?php endforeach;?>
                        	<?php endforeach;?>
                        <?php endif;?>
                        <?php if($this->error['captcha']):?>
                        	<?php foreach ($this->error['captcha'] as $value):?>
                        		<?php foreach ($value as $v):?>
                        		<?php if(!is_array($v)):?>
                        			<span style="color:red;font-size: 14px;"><?php print_r( $v)?></span><br>
                        		<?php endif;?>	
                        		<?php endforeach;?>
                        	<?php endforeach;?>
                        <?php endif;?>
                                               <?php echo $this->form;?>
<!--                         <form action="" method="post" id="contactForm" name="contactForm"> -->
<!--                             <div class="form"> -->
<!--                                 <label>Họ & Tên (*)</label> -->
<!--                                 <div class="input"> -->
<!--                                     <span class="name"></span> -->
<!--                                     <input type="text" class="Ten"  name="name" id="yourname" /> -->
<!--                                 </div> -->
<!--                             </div> -->
<!--                             <div class="form"> -->
<!--                                 <label>Email (*)</label> -->
<!--                                 <div class="input"> -->
<!--                                     <span class="email"></span> -->
<!--                                     <input type="text" class="Email"  name="email" id="email" /> -->
<!--                                 </div> -->
<!--                             </div> -->
<!--                             <div class="form"> -->
<!--                                 <label>Chủ đề (*)</label> -->
<!--                                 <div class="input"> -->
<!--                                     <span class="website"></span> -->
<!--                                     <input type="text" class="ChuDe" name="subject" id="tele"/> -->
<!--                                 </div> -->
<!--                             </div> -->
<!--                             <div class="form"> -->
<!--                                 <label>Nội dung (*)</label> -->
<!--                                 <textarea name="NoiDung" rows="10" cols="20"></textarea> -->
<!--                             </div> -->
<!--                             <div class="form2"> -->
<!--  <a  onclick="document.myform.submit()" class="send"><input type="submit" class="" value="Send Message" /></a>
<!--                             </div> -->
                            
<!--                         </form> -->

                        <div class="alertMessage"></div>
                    </div>
                    </div>
                    <!-- /Single -->
                    
                </div>
                <!-- /Main Content -->
                
                <!-- Left Sidebar -->
                <div class="column-one-third">


                    <div class="sidebar">
                        <h5 class="line"><span>Video</span></h5>
                        <?php if($this->Videos): ?>
                            <?php foreach($this->Videos as $value): ?>
                                <div class="full-frame" style="width: 320px; height: 300px; overflow: hidden;"><?php echo $value['Video']; ?></div>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <style>
                            iframe{ width: 280px;}
                        </style>
                    </div>
                    
                    <div class="sidebar">
                    	<h5 class="line"><span>QUẢNG CÁO</span></h5>
                    	<?php if($this->QuangCao):?>
                        <ul class="ads125">
                        <?php foreach ($this->QuangCao as $value):?>
                        <?php if(Websitefront_Model_Lienket::checkImage($value['Id'])):?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getImage($value['Id']);?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php else:?>
                        	<li><a href="<?php echo $value['Link']?>"><img src="<?php echo $this->baseUrl(). Websitefront_Model_Lienket::getDefaultImage();?>"	title="<?php echo $value['TieuDe']?>" alt="<?php echo $value['TieuDe']?>" /></a></li>
                        <?php endif;?>	
                        <?php endforeach;?>    
                        </ul>
                        <?php endif;?>
                    </div>
                    
                    <div class="sidebar">
				<div id="tabs">
					<ul>
						<li><a href="#tabs1">Gần nhất</a></li>
						<li><a href="#tabs2">Phổ biến</a></li>
						<li><a href="#tabs3">Bình luận</a></li>
					</ul>
					<div id="tabs1">
						<ul>
                                <?php if($this->TinMoiNhat):?>
                                <?php foreach ($this->TinMoiNhat as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo PublicdetailController::strimTitle($value['TieuDe']);?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?>   
                                </ul>
					</div>
					<div id="tabs2">
						<ul>
                                	 <?php if($this->TinXemNhieu):?>
                                <?php foreach ($this->TinXemNhieu as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
					<div id="tabs3">
						<ul>
                                	 <?php if($this->LuotBL):?>
                                <?php foreach ($this->LuotBL as $value):?>
                                	<li><a
								href="<?php echo $this->baseUrl ().'/websitefront/'.Websitefront_Model_Tintuc::getLink($value['Cate'], $value['Alias'])?>"
								class="title"><?php echo $value['TieuDe'];?>.</a> <span
								class="meta"><?php echo $value['NgayTao'];?></span> <span
								class="rating"><span style="width: 70%;"></span></span></li>
                                  <?php endforeach;?>  
                                 <?php endif;?> 
                                </ul>
					</div>
				</div>
			</div>
                    
                    
                    
                </div>
                <!-- /Left Sidebar -->
   
        </section>
<!--[if lt IE 9]> <script type="text/javascript" src="js/html5.js"></script> <![endif]-->


	
	
		
<!-- Google Map API v3 -->

    