<script type="text/javascript">
	var url;
	
	$(function(){
		$('#dg').edatagrid({
			url: 'lienket/json'
		});
	});
	
	function add(){
		$('#dlg').dialog('open').dialog('setTitle','Thêm Liên Kết');	
		$('#fm').form('clear');
		url = 'lienket/add';
	}

	function edit(){
		var row = $('#dg').datagrid('getSelected');
		if (row){
			$('#dlg').dialog('open').dialog('setTitle','Sửa');
			$('#fm').form('load',row);
			url = 'lienket/update/Id/'+ row.Id +'/TieuDe/'+ row.TieuDe 
				+'/TrangThai/'+row.TrangThai;
			
		}else{
			$.messager.show({
				title:'Thông báo',
				msg:'Không có bản ghi nào được chọn!',
				timeout:5000,
				showType:'slide'
			});
		}
	}

	function del(){
		var rows = $('#dg').datagrid('getSelections');
		
		
		items = rows.length;
		if (items > 0){
			$.messager.confirm('Thông báo','Bạn có chắc chắn muốn '+items+' phần tử xóa?',function(r){
				if (r){
					$.post('lienket/del',{items:rows},function(result){
						if (result.success){
							$('#dg').datagrid('reload');	
							show_messager('Cập nhật dữ liệu thành công!');
						} else {
							show_messager('Cập nhật dữ liệu không thành công!');
						}
					},'json');
				}
			});
		}else{
			show_messager('Không có bản ghi nào được chọn!');
		}
	}

	function save(){
		$('#fm').form('submit',{
			url: url,
			onSubmit: function(){
				return $(this).form('validate');
			},
			success: function(result){
				var result = eval('('+result+')');
				if (result.success){
					$('#dlg').dialog('close');		
					$('#dg').datagrid('reload');	
				} else {
					$.messager.show({
						title: 'Error',
						msg: result.msg
					});
				}
			}
		});
	}
</script>
<!-- Begin Datagrid -->
<table id="dg" title="Hình Ảnh" style="width: 100%;" toolbar="#toolbar"
	pagination="true" idField="id" rownumbers="true" nowrap="true"
	data-options="border:false,fit:true,singleSelect:true,fitColumns:false,selectOnCheck:false,checkOnSelect:false">
	<thead>
		<tr>
			<th field="TieuDe" width="200" sortable="true">Liên Kết</th>
			<th field="Link" width="150" sortable="true">Link</th>
			<th field="L" width="150" sortable="true">Loại</th>
			<th field="T" width="430" sortable="true">Trạng Thái</th>
			<th field="Id" data-options="hidden:true">Id</th>
		</tr>
	</thead>
</table>
<div id="toolbar" style="padding: 5px; height: auto;">
	<a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true"
		onclick="add()">Thêm</a> <a href="#" class="easyui-linkbutton"
		iconCls="icon-edit" plain="true" onclick="edit()">Sửa</a> <a href="#"
		class="easyui-linkbutton" iconCls="icon-remove" plain="true"
		onclick="del()">Xóa</a>
</div>
<!-- End DataGrid -->

<!-- Begin Form -->
<div id="dlg" class="easyui-dialog"
	style="width: 350px; height: 450px; background: #e7e7ef; padding: 10px;"
	closed="true" buttons="#dlg-buttons" modal="true">
	<form id="fm" method="post" enctype="multipart/form-data">
		<table border="0" width="100%" cellspacing="0" cellpadding="4"
			class="tblForm">
			<tr>
				<td width="100px;">
					<div>Tiêu Đề:</div>
				</td>
				<td class="2Col"><input id="TieuDe" name="TieuDe"
					class="easyui-validatebox" style="width: 200px"
					onkeypress="return beta(event)"></td>
			</tr>
			<tr>
				<td width="100px;">
					<div>Sắp Xếp:</div>
				</td>
				<td class="2Col"><input id="SapXep" name="SapXep"
					class="easyui-validatebox" style="width: 200px"
					onkeypress="return beta(event)"></td>
			</tr>
			<tr>
				<td>
					<div>Link:</div>
				</td>
				<td class="2Col">
					<!-- thay doi ten class easyui-text thanh  easyui-validatebox--> <input
					id="Link" name="Link" data-options="" class="easyui-text"
					style="width: 200px">
				</td>
			</tr>
			<tr>
				<td>
					<div>Hình ảnh:</div>
				</td>
				<td class=""><input type="file" id="HinhAnh" name="HinhAnh" /><img
					src="" /></td>
			</tr>
			<tr>
				<td>
					<div>Loại:</div>
				</td>
				<td class=""><input id="Loai" name="Loai"
					style="border: 1px solid #ccc; width: 120px;"
					class="easyui-combobox " url="lienket/getLoai" textField="TieuDe"
					valueField="Id" /></td>
			</tr>
			<tr>
				<td>
					<div>Trạng Thái:</div>
				</td>
				<td class=""><select id="TrangThai" name="TrangThai"
					style="width: 200px;" class="easyui-combobox">
						<option selected="selected" value="1">Cho phép</option>
						<option value="0">Không cho phép</option>
				</select></td>
			</tr>
		</table>
	</form>
</div>
<div id="dlg-buttons">
	<a href="#" class="easyui-linkbutton" iconCls="icon-ok"
		onclick="save()">Câp nhật</a> <a href="#" class="easyui-linkbutton"
		iconCls="icon-cancel" onclick="javascript:$('#dlg').dialog('close')">Hủy
		bỏ</a>
</div>
<!-- End From -->